### ISSUE TITLE
ee_definefiles

### ISSUE THREAD

**Issue by Evigouse** [roschkoenig/Dynamics_Matrices#2]
Hello, when I run ee_synthgen, it says miss function ee_definefiles, could you offer this function?

**Comment by roschkoenig** [comment]
Woudl love to help - but alas seem to have lost the file. I think all the function does is go through the relevant folder and find all files that meet a certain condition (in terms of naming convention) and then returns a part of the filestring for each of the files into the p and c varible.

**Comment by Evigouse** [comment]
Thank you very much, I will try to accomplish this myself.
